version: '3'
services:
  test-mysql:
    container_name: test-mysql
    image: mysql:5.7
#    network_mode: host
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
